 
export const BLOG_POST_LIST_RECIEVED = 'BLOG_POST_LIST_RECIEVED';
export const BLOG_POST_LIST_ERROR = 'BLOG_POST_LIST_ERROR';
export const BLOG_POST_LIST_ADD = 'BLOG_POST_LIST_ADD';
export const BLOG_POST_LIST_REQUST = 'BLOG_POST_LIST_REQUST';
export const BLOG_POST_RECIEVED = 'BLOG_POST_RECIEVED';
export const BLOG_POST_ERROR = 'BLOG_POST_ERROR';
export const BLOG_POST_REQUST = 'BLOG_POST_REQUST';
